### ISSUE TITLE
List of languages in development

### ISSUE THREAD

**Issue by rkcosmos** [JaidedAI/EasyOCR#91] opened 2020-07-10 04:20 UTC
I will update/edit this issue to track development process of new language. The current list is

**Group 1 (Arabic script)**
- Arabic (DONE, August, 5 2020)
- Uyghur (DONE, August, 5 2020)
- Persian (DONE, August, 5 2020)
- Urdu (DONE, August, 5 2020)

**Group 2 (Latin script)**
- Serbian-latin (DONE, July,12 2020)
- Occitan (DONE, July,12 2020)

**Group 3 (Devanagari)**
- Hindi (DONE, July,24 2020)
- Marathi (DONE, July,24 2020)
- Nepali (DONE, July,24 2020)
- Rajasthani (NEED HELP)
- Awadhi, Haryanvi, Sanskrit (if possible)

**Group 4 (Cyrillic script)**
- Russian (DONE, July,29 2020)
- Serbian-cyrillic (DONE, July,29 2020)
- Bulgarian (DONE, July,29 2020)
- Ukranian (DONE, July,29 2020)
- Mongolian (DONE, July,29 2020)
- Belarusian (DONE, July,29 2020)
- Tajik (DONE, April,20 2021)
- Kyrgyz (NEED HELP)

**Group 5**
- Telugu  (DONE, November,17 2020)
- Kannada  (DONE, November,17 2020)

**Group 6 (Language that doesn't share characters with others)** 
- Tamil (DONE, August, 10 2020)
- Hebrew (ready to train)
- Malayalam (ready to train)
- Bengali + Assamese (DONE, August, 23 2020)
- Punjabi (ready to train)
- Abkhaz (ready to train)

**Group 7 (Improvement and possible extra models)**
- Japanese version 2 (DONE, March, 21 2021)+ vertical text
- Chinese version2 (DONE, March, 21 2021)+ vertical text
- Korean version 2(DONE, March, 21 2021)
- Latin version 2 (DONE, March, 21 2021)
- Math + Greek?
- Number+symbol only

**Guideline for new language request**

To request a new language support, I need you to send a PR with 2 following files

1. In folder [easyocr/character](https://github.com/JaidedAI/EasyOCR/tree/master/easyocr/character), we need 'yourlanguagecode_char.txt' that contains list of all characters. Please see format/example from other files in that folder.
2. In folder [easyocr/dict](https://github.com/JaidedAI/EasyOCR/tree/master/easyocr/dict), we need 'yourlanguagecode.txt' that contains list of words in your language. On average we have ~30000 words per language with more than 50000 words for popular one. More is better in this file.

If your language has unique elements (such as 1. Arabic: characters change form when attach to each other + write from right to left 2. Thai: Some characters need to be above the line and some below), please educate me with your best ability and/or give useful links. It is important to take care of the detail to achieve a system that really works.

Lastly, please understand that my priority will have to go to popular language or set of languages that share most of characters together (also tell me if your language share a lot of characters with other). It takes me at least a week to work for new model. You may have to wait a while for new model to be released.

**Comment by yossibiton** [comment] 2020-07-10 05:42
Why won't you share the training code, so people could train the model by themself ?

**Comment by madrugado** [comment] 2020-07-10 05:59
For group 4 you could add Ukrainian, Bulgarian, and may be Mongolian, although it is not Slavic it uses Cyrillic script.

**Comment by edloginova** [comment] 2020-07-10 06:27
Do you plan to only work with human languages? It would be amazing to add a model to recognize mathematical formulas.

**Comment by manohar-cyber** [comment] 2020-07-10 11:04
I guess Tamil, Telugu can be added to one group because they belongs to a language group called 'Dravidian'. Meaning they relate to each other in terms of grammar, word arrangement.Two other popular( in India) language, which belong to that family can also be added to that group— Kannada and Malayalam (For further info— https://en.m.wikipedia.org/wiki/Dravidian_languages). Moreover Telugu and kannada share some common alphabets and words. I will be adding alphabet and words of kannada language for language request. 
Great project, keep it up👍

**Comment by bgmastermind** [comment] 2020-07-10 11:58
For Group 4
Bulgarian 
dict [bg.txt](https://github.com/JaidedAI/EasyOCR/files/4902956/bg.txt)
char [bg_char.txt](https://github.com/JaidedAI/EasyOCR/files/4902960/bg_char.txt)

**Comment by upadhyayprakash** [comment] 2020-07-10 12:13
I'd highly recomend supporting Devanagiri Script (Wiki - https://en.wikipedia.org/wiki/Devanagari), which is the fourth most widely adopted writing system in the world. Please go through the wikipedia link to understand its wide spread across most Ancient Languages including Sanskrit, Hindi, Marathi, Awadhi, Haryanvi.

I see you have included "Hindi" as a target language, which of course, is the most spoken language in the Indian Subcontinent.

If you could let me know what's the current word-count you have (maybe share the "dict" & "alphabets" directory), I can do continue with the research to share different parts of the Language.

Hindi has 47 primary alphabets (including 14 Vowels & 33 Consonants).

You can contact me @ prakash.upadhyay93@yahoo.com

**Comment by arashjafari** [comment] 2020-07-10 15:01
Can i help for the Persian (Farsi) language ? I can supply some popular words and characters 

@rkcosmos

**Comment by junaidgirkar** [comment] 2020-07-10 15:55
Can i contribute in any way. I am fluent in Hindi alongside English. Also I may be of help in the programming section. I know Python, C and Java in languages. Am good in front-end with HTML, CSS and JavaScript (basic).

**Comment by manmeet3591** [comment] 2020-07-10 18:43
I recommend adding Punjabi language which is the 10th most spoken language around the world. 
[pb_char.txt](https://github.com/JaidedAI/EasyOCR/files/4904817/pb_char.txt)

**Comment by rkcosmos** [comment] 2020-07-11 07:42
@edloginova After doing human language, we can explore math as well. 

@upadhyayprakash Lists are here  [easyocr/character](https://github.com/JaidedAI/EasyOCR/tree/master/easyocr/character) and [easyocr/dict](https://github.com/JaidedAI/EasyOCR/tree/master/easyocr/dict)

@arashjafari looks like we already have both words and char. You can recheck if everything is alright. 

@junaidgirkar sounds good, I'll keep in mind. May call you for help.

**Comment by Vijayabhaskar96** [comment] 2020-07-11 16:01
> Why won't you share the training code, so people could train the model by themself ?

I agree with this, If the training code and sample dataset are provided, many can train the model for their language. With free GPU services like Google colab and Kaggle Kernels, anyone can train them online and contribute much faster.

**Comment by rkcosmos** [comment] 2020-07-12 00:03
> Why won't you share the training code, so people could train the model by themself ?

@yossibiton @Vijayabhaskar96 because it's still not straightforward training process. Even I have to think carefully when creating model. Will share later when it's clean. Please don't pressure me, I am doing a lot of work for free.

**Comment by rahilwazir** [comment] 2020-07-12 01:59
@rkcosmos Can we add support for the language Urdu? It is very similar with Persian and Arabic (not much complexities of arabic though).

**Comment by Vijayabhaskar96** [comment] 2020-07-12 03:47
> > Why won't you share the training code, so people could train the model by themself ?
> 
> @yossibiton @Vijayabhaskar96 because it's still not straightforward training process. Even I have to think carefully when creating model. Will share later when it's clean. Please don't pressure me, I am doing a lot of work for free.

Sorry I made you feel this way, I didn't mean to pressurize you. I just wanted to help. Take your time, you're doing great work!

**Comment by fnasim** [comment] 2020-07-12 05:00
For Group 1, could you add Urdu to that group? Urdu is very similar to Arabic and Persian and I've just submitted the PR for the character list and a dictionary. So it should be ready to go!

**Comment by loayamin** [comment] 2020-07-12 21:53
This might help for Arabic:

https://github.com/OSINTAI/Arabic_Words

**Comment by sardasumit** [comment] 2020-07-13 15:45
I added Marathi character and dictionary file please look into it [easyocr/character/mr_char.txt](easyocr/dict/mr.txt)

**Comment by sardasumit** [comment] 2020-07-13 15:47
i added Marathi character and dictionary data set file please train it

**Comment by rkcosmos** [comment] 2020-07-14 01:37
> i added Marathi character and dictionary data set file please train it
> [mr.txt](https://github.com/JaidedAI/EasyOCR/files/4913549/mr.txt)

@sardasumit  did you forget a link for mr_char.txt?

**Comment by sardasumit** [comment] 2020-07-14 01:51
> > i added Marathi character and dictionary data set file please train it
> > [mr.txt](https://github.com/JaidedAI/EasyOCR/files/4913549/mr.txt)
> 
> @sardasumit did you forget a link for mr_char.txt?

@rkcosmos it is same like Hindi character 
[mr_char.txt](https://github.com/JaidedAI/EasyOCR/files/4916068/mr_char.txt)

**Comment by nishad** [comment] 2020-07-15 10:35
@rkcosmos 
Malayalam (https://en.wikipedia.org/wiki/Malayalam), belongs to Group 6.
https://github.com/JaidedAI/EasyOCR/pull/143
This PR contains character and word lists.

**Comment by imvladikon** [comment] 2020-07-15 18:04
Hi! Thanks for your work. Some notes about Hebrew, there are some ending form of letters (it means that some letter is changing their form if they are placed at the end of words) https://en.wikipedia.org/wiki/Final_form Also there are diacritical signs https://en.wikipedia.org/wiki/Niqqud that used to represent vowels or distinguish between alternative pronunciations of letters (in Arabic also there are final forms(and not only) and diacritical signs) I didn't provide diacritical signs, assume it's better to train first of all without them

**Comment by imvladikon** [comment] 2020-07-15 23:18
remembered the important thing. in Hebrew, there is cursive(https://en.wikipedia.org/wiki/Cursive_Hebrew) and sometimes people mixed it up together with usual writing even using printed matter, it's the same letters (chars), but let's say it's another font (e.g. https://opensiddur.org/wp-content/uploads/fonts/display-font-charmap.php?fnt=DorianCLM-Italic ) maybe it's also better not to implement immediately, don't know

**Comment by rkcosmos** [comment] 2020-07-16 08:45
@nishad Malayalam and Tamil are both Dravidian but do not use the same script. So I have to build 2 model.
@imvladikon ok, will try to keep this in mind when building Hebrew model.

**Comment by rkcosmos** [comment] 2020-07-16 15:41
Question for Indian: I'm looking into Hindi char and dict, there are a lot of chars seen in word list but not in char list. Examples are
`['ा', '्', 'ि', 'ी', 'ं', 'ो', 'ु', 'ँ', 'ू', 'ड़', 'ै']`. What are these symbols?

**Comment by Vijayabhaskar96** [comment] 2020-07-16 15:49
@rkcosmos Those are part of the existing alphabet when combined it creates a new alphabet, I think the technical term is grapheme? I'm not sure. I would like to know they render fine or something happens like it did with Tamil.

**Comment by rkcosmos** [comment] 2020-07-17 03:19
@Vijayabhaskar96 So far, Devanagari doesn't have any problem. They support unicode well.

**Comment by imvladikon** [comment] 2020-07-17 14:23
another addition about Hebrew;) and it's important. some diacritic signs are important, like [geresh](https://en.wikipedia.org/wiki/Geresh) and [gershayim](Gershayim).  using geresh with ג ז צ  we could use for the sounds - j g, ch, that are not represented in the alphabet  and double geresh (gershayim) it's for widely spread short phrase, words (kitsur) most famous is the תנ"ך (Tanakh). Sometimes people could use usual quotation marks (apostrophe) instead of typing geresh or gershayim (e.g. תנ''ך)

**Comment by omprakash-jena** [comment] 2020-07-19 07:48
Can you please simulate it for Odia Language which is also a classical language of India coming under group 6.

**Comment by rkcosmos** [comment] 2020-07-19 07:53
@omprakash-jena You can create a pull request to add files. Or you can also attach files in comment here.

**Comment by rkcosmos** [comment] 2020-07-21 05:10
Question for India: I'm testing Devanagari model with this 
![Uploading hi1.jpg…](image) .
The result is `['50', '40', 'बसझरकर', 'SPEED', 'मािकट', 'LIMIT', 'BASRURKAR', 'MARKET']`.

The problem is with ` मािकट`. It doesn't look like what is written in the original image. But when I do
 `for c in 'मािकट': print(c)`, I got `म ा  ि  क  ट` which looks quite right. What's going on here?

**Comment by nishad** [comment] 2020-07-21 10:15
@rkcosmos 

Both devanagari strings are identified differently from the image.
They are `बसरूरकर` and `मार्किट`.
These characters join (`र+ ्+ क+ ि` ), and renders as `र्कि`

**Comment by rkcosmos** [comment] 2020-07-21 10:34
@nishad  Wow, this is really hard. It means OCR need to understand how to combine character in a very complex way.

**Comment by nishad** [comment] 2020-07-21 10:42
@rkcosmos, this is complex and I am not knowledgeable in explaining this.
@santhoshtr could you please share your expertise ?

**Comment by Vijayabhaskar96** [comment] 2020-07-21 13:31
@rkcosmos I don't speak Hindi, but this is interesting. I think the problem is hi_char.txt doesn't have all the chars. For example: र् is not there but र and ् are present while र + ्  = र् 
If you look at Tamil chars all the alphabets with those extra parts are present instead of just including the root alphabet and the extra parts separately.  i.e க + ா = கா, both க and கா are present in ta_char.txt but not  ா

**Comment by rkcosmos** [comment] 2020-07-21 14:57
@Vijayabhaskar96 It depends on how many combinations are there for each language. It's possible to do both ways. For example, I did Thai before with separated characters. We have something like ท +   ี +  ่  = ที่. First three characters are in the list but the combined form is not. For Thai, I use separated character because number of all possible combinations is just too much to imagine. For Tamil, you have 325 combined forms, I think it should be doable. Now for Hindi, they have र्कि which is a combined form of 4 separated characters! I would guess their number of all possible combined form is extremely large. So we might have to go with separated char way. I just hope that my current neural network's setting can learn such complexity. Will let everyone know in a few days if it works or not.

**Comment by Vijayabhaskar96** [comment] 2020-07-21 15:50
According to the link In my previous comment there about 500 combinations in Hindi, I don't think even with all combinations that aren't in that link it will exceed 2000+ characters, Telugu list has 2000+ chars. So try what works best, findings from this experiment may simplify other language training approaches.

**Comment by imvladikon** [comment] 2020-07-21 16:49
Belarusian is ready? [commit](https://github.com/JaidedAI/EasyOCR/commit/25faa43950f1c53d566664bdaf5cf911ff9ffc02) probably list need update

**Comment by rkcosmos** [comment] 2020-07-24 02:38
![example3](https://user-images.githubusercontent.com/12238328/88356219-4e8c7000-cd91-11ea-9bd2-58814815f508.png)

Version 1.1.5 now support Devanagari script. Please test, feedback and spread the words to your community.

**Comment by sardasumit** [comment] 2020-07-24 02:43
Hello 
Please send me training code I will look into this issue.

Thank you

Sent from Yahoo Mail on Android 
 
  On Tue, 21 Jul 2020 at 7:01 pm, Vijayabhaskar<notifications@github.com> wrote:   


@rkcosmos I don't speak Hindi, but this is interesting. I think the problem is hi_char.txt doesn't have all the chars. For example: र् is not there but र and ् are present while र + ् = र्
If you look at Tamil chars all the alphabets with those extra parts are present instead of just including the root alphabet and the extra parts separately. i.e க + ா = கா, both க and கா are present in ta_char.txt but not ா

**Comment by zoghal** [comment] 2020-07-24 19:39
Hello dear
Can i help for the Persian (Farsi) language ? 
-I can supply some popular words and characters and also i working in the field of Persian typeface design & [Libre persian fonts](https://github.com/Font-Store/)

**Comment by rkcosmos** [comment] 2020-07-24 22:09
@zoghal please add more words to [easyocr/character/fa.txt](https://github.com/JaidedAI/EasyOCR/tree/master/easyocr/character/fa.txt)

**Comment by rkcosmos** [comment] 2020-07-28 22:33
Cyrillic script (Russian, Serbian(cyrillic), Belarusian, Bulgarian, Mongolian, Ukrainian) is available for testing in last update (not on pip yet), please test and feedback.

**Comment by imvladikon** [comment] 2020-07-29 20:02
Belarusian, Russian, Ukrainian:
https://colab.research.google.com/drive/1Sy1endzzbommR2b5pyw7YIoa8CIV-jkN?usp=sharing
the quality is not so bad, in Ukrainian, there is an additional sign, apostrophe ’ for softness or on the contrary for emphasizing hard consonant (like ім'я) depends on some phonetical rules, cases.

**Comment by rkcosmos** [comment] 2020-07-30 00:57
@imvladikon Thanks for the analysis, it's very useful. I'll keep in mind the special character issue for next fine-tuning. For low-resolution image, you might need to change some parameters to get better result. For example, I would try `mag_ratio = 1.2` (that's zooming by 20%). One thing I don't understand in your colab is with expected result of `ulica_be.jpg`. It's the phase 'лінгвістичний'. Is it a typo or your language has special rule to combine characters?

**Comment by imvladikon** [comment] 2020-07-30 06:21
@rkcosmos yeah, it's a typo) for the Belarusian language should be "лінгвістычны", fixed it. this word accidentally was written on Ukrainian "лінгвістичний" ("linguistic")

**Comment by rkcosmos** [comment] 2020-08-04 04:40
Arabic is now supported in v1.1.6. To use the last version, you need to uninstall first
`pip uninstall easyocr`

and install directly from source code
`pip install git+git://github.com/jaidedai/easyocr.git`

please try and feedback.

**Comment by Vijayabhaskar96** [comment] 2020-08-04 04:43
You can do that in a single command itself.
`pip install git+git://github.com/jaidedai/easyocr.git --upgrade` no need to uninstall manually.

**Comment by Vijayabhaskar96** [comment] 2020-08-10 19:09
@rkcosmos Thanks for adding support for Tamil, tested few images and it worked well, some images required fiddling with the args for better results, but anyway great job for overcoming the unicode issues, may I know what you did? And if you used pyvips as I suggested how did it go? Can you explain shortly?

**Comment by fnasim** [comment] 2020-08-10 19:12
@rkcosmos You marked Urdu as done (great news!). Can I try it in the latest?

**Comment by rahilwazir** [comment] 2020-08-10 19:42
@fnasim @rkcosmos I've been trying to test urdu with multiple variations, although it's not completely there yet, but it's close. There are still some subtle differences.

The `بھائی` is recognized as `میں` ,`بجال` is recognized as `لکھیں` ,`ئیں` recognized as `اکھیں` etc.
I will continue to test more and share the results.

**Comment by fnasim** [comment] 2020-08-10 19:58
@rahilwazir Thank you for testing! Please keep a list of discrepancies and always keep track of the image you used (minimal is better). I tried a screen grab from bbc.com/urdu and it worked pretty well (100% accuracy based on quick visual inspection - GREAT start, kudos @rkcosmos ).

**Comment by fnasim** [comment] 2020-08-15 07:22
@rahilwazir here's the test I did - https://codepen.io/fnasim/pen/OJNNmPg. I've embedded the image and output json from easyocr on there so just hit 'Process' to see rectangles. Please feel free to click them.

@rkcosmos the OCR is pretty accurate but the confidence score is extremely low. Do you know why?

**Comment by ai-motive** [comment] 2020-09-02 01:20
If the math model is updated, what is the output of the input image?

![스크린샷, 2020-09-02 10-17-02](https://user-images.githubusercontent.com/69468134/91921164-cb522880-ed05-11ea-9987-6baf8766d90b.png)   ==>    ?

**Comment by SungmanHong** [comment] 2020-09-02 04:48
Can I run in Android via TF-lite?

**Comment by thammegowda** [comment] 2020-09-16 03:37
@rkcosmos Thanks for this awesome work.
I see that in Group 5, Kannada  is listed as "NEED HELP"
NOTE: I'd already sent PR with Kannada vocabulary https://github.com/JaidedAI/EasyOCR/pull/124 

we appreaciate if you could please move Kannada up in your priority. 
Is there anything I help you to speed up training the first version of OCR model for Kannada? Thx

**Comment by danielinux7** [comment] 2020-10-19 21:44
@rkcosmos Any update on this work? It's been a while since I have added the Abkhazian language!

**Comment by howard-haowen** [comment] 2020-11-10 08:56
I noticed there's no date for Group 7. I'm just wondering when "Chinese version2 + vertical text" will be released. The current Chinese model is excellent in many ways, but doesn't work for vertical texts. Thanks for keeping improving!

**Comment by rkcosmos** [comment] 2020-11-10 09:37
Hi everyone, sorry for a delay. We have been testing smaller network for faster processing time. Apart from this we also need to do things that can feed our mouths. I can't promise any timeline but we are working.

btw @thammegowda Kannada and Telugu characters may look similar but they are using different unicode character set. I may have to separate them into 2 models.

**Comment by SE2AI** [comment] 2020-12-01 01:55
any plans or roadmaps to supporting myanmar language?

**Comment by AnassKartit** [comment] 2020-12-17 16:26
any plans for french? how to help?

**Comment by alirezamohammadi01** [comment] 2021-01-22 20:30
hi how can i use Persian language ???
reader = easyocr.Reader(['ch_sim','fa']) 
result = reader.readtext('chinese.jpg')
why not work?

**Comment by kalai2033** [comment] 2021-01-27 16:03
Hi,
   Thanks for the great repo. I have to need to OCR different language images like 

az - Azerbaijani 
cs - Czech 
da - Danish
de - Deutsch
el - Greek Modern
en - English
es - Spanish, Castilian
et - Estonian
fi - finnish
fr - French
hr - croatian


This all languages uses ''latin.pth'' model for recognition. But it does not include characters other than English and german. For example i could not read any special characters like 

For example, if I read an image with the following Azerbaijani text:

**Ş** i r k **ə** t  n ü m a y **ə** n d **ə** s i 

it gives output as

Siket nümayandesi

**Comment by qbeer** [comment] 2021-02-02 11:07
Even if it is messy, I think a lot of us would be really happy if you shared your training code as well.

**Comment by KhayrulloevDD** [comment] 2021-03-16 03:52
Hello there! I can help you with tajik language, what do you need? Contact me dodullo.khayrulloev@gmail.com

**Comment by KhayrulloevDD** [comment] 2021-03-30 05:03
For Group 4
Tajik
[tajik.zip](https://github.com/JaidedAI/EasyOCR/files/6226274/tajik.zip)

**Comment by KhayrulloevDD** [comment] 2021-04-01 08:57
Hello there! Can you guys give me some feedback, so i know that had send you correct data for training tajik language, thank you!

**Comment by tsaidevin** [comment] 2021-04-15 08:40
Excuse me, will there be a chi_tra version2 _?

**Comment by rkcosmos** [comment] 2021-04-15 10:46
@tsaidevin yes.

**Comment by abhishekvermasg** [comment] 2021-04-20 03:19
Are model training scripts not there? If somebody wants to train on a new language. How can one contribute to betterment of model?

**Comment by DaniSubodh** [comment] 2021-04-21 18:04
Hi @rkcosmos, really impressive work with the OCR framework.
I couldn't find a code for Greek language [here](https://www.jaided.ai/easyocr/), but I see (Greek + math) in the development list above. Do you know if the **Greek** language itself will be supported anytime soon?

**Comment by PhonVanna** [comment] 2021-05-14 14:38
Hi @rkcosmos , really impressive work.
I am not sure whether you will add khmer language to it?

**Comment by JoeDelK** [comment] 2021-06-14 10:20
Hi @rkcosmos,

We created a dictionary and dict_char for the greek language, you can find it here:
[https://github.com/JaidedAI/EasyOCR/pull/461](url)

**Comment by KarmaCST** [comment] 2021-08-01 05:09
Can you add Dzongkha? Dzongkha is the national language of Bhutan and it is similar to the Tibetan Language. Similar to Thai language, it is written continuously from left to right and does not have a whitespace between words. Following paper discusses on next syllabus prediction for Dzongkha. https://doi.org/10.1016/j.jksuci.2021.01.001

**Comment by weihaulee** [comment] 2021-09-06 03:57
Hi @rkcosmos,
Is there any plan to add English （vertical text） and digits （vertical text）?

Thanks in advance.

**Comment by vneseresearcher** [comment] 2021-09-29 02:04
Hi @rkcosmos , Can you share the Japanese dataset you used to train?

**Comment by ajeetmishra** [comment] 2021-10-17 18:27
Hi @rkcosmos. Thank you very much for the efforts you are taking. Is there a plan to include the Indian languages - Gujarati and Oriya ?

**Comment by amirashe** [comment] 2021-11-10 16:42
hii @rkcosmos do you know if the hebrew will be ready soon? thnak a lot!

**Comment by FtmsdtHosseini** [comment] 2021-12-05 16:36
Hello, thank you for your great job.
I ran version 1.4.1 for Persian(Farsi), but the problem that I am facing is, Persian is written and read from right to left, but the model detects words from left to right. This confuses text detection and reduces the accuracy.
is there any solution to fix this issue?

**Comment by babraham123** [comment] 2021-12-09 09:53
Hi @rkcosmos, thanks so much for all the work you've put in. I've included a PR for the Amharic language, which is spoken by over 60 million people.
https://github.com/JaidedAI/EasyOCR/pull/616

One potential issue is that Amharic words contain a number of prefixes and suffixes to indicate the object, number of items, tense, gender, negation and so. Thus, a single verb may morph in a number of ways that are not all included in the dictionary.

**Comment by babraham123** [comment] 2021-12-09 09:57
Hi @rkcosmos, I also submitted a PR for the Tigrinya language, which is similar to Amharic and spoken by over 10 million people.
https://github.com/JaidedAI/EasyOCR/pull/615

It has the same mutation issue as Amharic. Also, Arabic numerals are very common despite having its own numeral system.

**Comment by 98-Jane** [comment] 2022-02-10 04:09
Question: Why Chinese dict is pinning rather than Chinese? In the dict folder, cannot find the Chinese dict(not pinying)?How to achieve this mapping relationship? If I want to add some words in Chinese dict, how do I add training data and dict?

**Closed** 2022-08-07 05:00 UTC
Labels: help wanted, Language Request

**Comment by Saranga99** [comment] 2022-09-01 09:36
does easyocr support Sinhala language?

**Comment by amits-ds** [comment] 2023-04-24 08:10
Hey, thank you for this Repo 🙏
Is there an update on a model for Hebrew OCR?

**Comment by minamohamadii** [comment] 2023-05-02 06:35
i want use farsi language but i see it is not fine tune on 5 farsi and fine tune on 5 arabic 
5 farsi = ۵ 
5 arabic = ٥
and it become a problem for me because it show me 0 in persian show me ٥ can you please improve farsi language ??? it help me so much

**Comment by ashudhatma** [comment] 2023-11-28 11:13
For Group 3 (Devanagari)
Request to add Gujarati Language
[gu.txt](https://github.com/JaidedAI/EasyOCR/files/13487204/gu.txt)
[gu_char.txt](https://github.com/JaidedAI/EasyOCR/files/13487208/gu_char.txt)

**Comment by nmermigas** [comment] 2024-02-14 20:56
Hey, I saw that the issue about the support of the greek language is completed and I can see the two required .txt documents about greek. However, I cannot find the greek language code ('gre' in the repo) in the list with the supported languages that is on the website. Is greek actually supported?

**Comment by haroon423** [comment] 2024-04-08 04:28
urdu language not supported Easyocr model ?

**Comment by AinazRafiei** [comment] 2024-05-18 14:23
> I will update/edit this issue to track development process of new language. The current list is
> 
> **Group 1 (Arabic script)**
> 
> * Arabic (DONE, August, 5 2020)
> * Uyghur (DONE, August, 5 2020)
> * Persian (DONE, August, 5 2020)
> * Urdu (DONE, August, 5 2020)
> 
> **Group 2 (Latin script)**
> 
> * Serbian-latin (DONE, July,12 2020)
> * Occitan (DONE, July,12 2020)
> 
> **Group 3 (Devanagari)**
> 
> * Hindi (DONE, July,24 2020)
> * Marathi (DONE, July,24 2020)
> * Nepali (DONE, July,24 2020)
> * Rajasthani (NEED HELP)
> * Awadhi, Haryanvi, Sanskrit (if possible)
> 
> **Group 4 (Cyrillic script)**
> 
> * Russian (DONE, July,29 2020)
> * Serbian-cyrillic (DONE, July,29 2020)
> * Bulgarian (DONE, July,29 2020)
> * Ukranian (DONE, July,29 2020)
> * Mongolian (DONE, July,29 2020)
> * Belarusian (DONE, July,29 2020)
> * Tajik (DONE, April,20 2021)
> * Kyrgyz (NEED HELP)
> 
> **Group 5**
> 
> * Telugu  (DONE, November,17 2020)
> * Kannada  (DONE, November,17 2020)
> 
> **Group 6 (Language that doesn't share characters with others)**
> 
> * Tamil (DONE, August, 10 2020)
> * Hebrew (ready to train)
> * Malayalam (ready to train)
> * Bengali + Assamese (DONE, August, 23 2020)
> * Punjabi (ready to train)
> * Abkhaz (ready to train)
> 
> **Group 7 (Improvement and possible extra models)**
> 
> * Japanese version 2 (DONE, March, 21 2021)+ vertical text
> * Chinese version2 (DONE, March, 21 2021)+ vertical text
> * Korean version 2(DONE, March, 21 2021)
> * Latin version 2 (DONE, March, 21 2021)
> * Math + Greek?
> * Number+symbol only
> 
> **Guideline for new language request**
> 
> To request a new language support, I need you to send a PR with 2 following files
> 
> 1. In folder [easyocr/character](https://github.com/JaidedAI/EasyOCR/tree/master/easyocr/character), we need 'yourlanguagecode_char.txt' that contains list of all characters. Please see format/example from other files in that folder.
> 2. In folder [easyocr/dict](https://github.com/JaidedAI/EasyOCR/tree/master/easyocr/dict), we need 'yourlanguagecode.txt' that contains list of words in your language. On average we have ~30000 words per language with more than 50000 words for popular one. More is better in this file.
> 
> If your language has unique elements (such as 1. Arabic: characters change form when attach to each other + write from right to left 2. Thai: Some characters need to be above the line and some below), please educate me with your best ability and/or give useful links. It is important to take care of the detail to achieve a system that really works.
> 
> Lastly, please understand that my priority will have to go to popular language or set of languages that share most of characters together (also tell me if your language share a lot of characters with other). It takes me at least a week to work for new model. You may have to wait a while for new model to be released.

There is a misstake in name of Group 1.It has to be Persian scripts.If you search you will see that Persian is the mother language of others and the rest Arabic, Urdu and Uyghur were taken from it(Persian Language).

**Comment by bereket42** [comment] 2024-05-21 07:19
Please let me know if Amharic or Tigrinya can be added, thanks!
https://github.com/JaidedAI/EasyOCR/issues/91#issuecomment-989687935
https://github.com/JaidedAI/EasyOCR/issues/91#issuecomment-989690558

**Comment by DanielVegaVega** [comment] 2024-07-04 08:48
> Hey, I saw that the issue about the support of the greek language is completed and I can see the two required .txt documents about greek. However, I cannot find the greek language code ('gre' in the repo) in the list with the supported languages that is on the website. Is greek actually supported?

@nmermigas looking for Greek as well. Could you find a way to "train" EasyOCR for it? Or is it something that the developer team must train?

**Comment by IordanisSap** [comment] 2024-07-09 06:36
I am also looking for Greek.

**Comment by snimavat** [comment] 2024-09-11 05:27
Gujarati language please

**Comment by danhertztech** [comment] 2024-11-17 22:11
Any update on whether EasyOCR will be adding support for Hebrew, and if so, when? Thank you.

[https://www.jaided.ai/easyocr/](https://www.jaided.ai/easyocr/)

**Comment by alexeyev** [comment] 2024-12-05 07:48
Hi, made a pull request for Kyrgyz language: https://github.com/JaidedAI/EasyOCR/pull/1344

What are the next steps to help you move forward with it? Thanks.

**Comment by alexeyev** [comment] 2024-12-05 14:09
@rkcosmos Also, can you clarify the status of the project please? Is it still alive? : )

**Comment by danhertztech** [comment] 2025-04-19 17:55
Any word on whether Hebrew will be supported? Thank you.

**Comment by NeighborhoodCoding** [comment] 2025-04-21 01:13
Nice work

**Comment by marnex** [comment] 2025-05-21 12:05
I hit a issue, it sounds that easyOCR fails to support greek character as below. Does easyOCR support Greek langague? If yes, how to make it support? Thanks.
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 77
     39 plt.show()
     41 
     42 #image = image.resize((image.width * 2, image.height * 2), Image.LANCZOS)  
     43 #image = ImageEnhance.Contrast(image).enhance(2)
   (...)
     75   
     76 #reader = easyocr.Reader(['ch_sim', 'en'])
---> 77 reader = easyocr.Reader(
     78    ['ch_sim', 'en', 'ell'],
     79     model_storage_directory='/Users/sunnychen/.EasyOCR/model'  
     80 )
     82 result = reader.readtext(image_path)
     83 #for bbox, ocr_text, conf in result:
     84 #    print(ocr_text)
     85 
   (...)
     89 
     90 #

File ~/Documents/project/cosing/sunny/lib/python3.9/site-packages/easyocr/easyocr.py:109, in Reader.__init__(self, lang_list, gpu, model_storage_directory, user_network_directory, detect_network, recog_network, download_enabled, detector, recognizer, verbose, quantize, cudnn_benchmark)
    107 unknown_lang = set(lang_list) - set(all_lang_list)
    108 if unknown_lang != set():
--> 109     raise ValueError(unknown_lang, 'is not supported')
    110 # choose recognition model
    111 if lang_list == ['en']:

ValueError: ({'ell'}, 'is not supported')`
